# Generated by Django 4.0.8 on 2026-03-26 13:16

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranscodingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('input_url', models.URLField(max_length=512)),
                ('output_path', models.CharField(max_length=512)),
                ('webhook_url', models.URLField(blank=True, max_length=512, null=True)),
                ('storage_config', models.JSONField(default=dict)),
                ('drm_config', models.JSONField(default=dict)),
                ('meta_data', models.JSONField(default=dict)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Queued'), (2, 'Downloading'), (3, 'Transcoding'), (4, 'Packaging'), (5, 'Uploading'), (6, 'Completed'), (7, 'Failed')], default=1)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
