# Generated by Django 5.2.12 on 2026-03-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranscodingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_url', models.URLField()),
                ('output_path', models.CharField(max_length=512)),
                ('webhook_url', models.URLField(blank=True, max_length=512, null=True)),
                ('storage_config', models.JSONField(default=dict)),
                ('drm_config', models.JSONField(default=dict)),
                ('meta_data', models.JSONField(default=dict)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Queued'), (2, 'Downloading'), (3, 'Transcoding'), (4, 'Packaging'), (5, 'Uploading'), (6, 'Completed'), (7, 'Failed')], default=1)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
